sudo: required

language: node_js

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

node_js:
  - "v8.12.0"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "cd tests/behave"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip install selenium"
  - "pip install --ignore-installed behave"
  - "cd ../.."
  # - "sudo pip install --upgrade pip"
  # - "sudo pip install selenium"
  # - "sudo pip install --ignore-installed behave"

install:
  - "npm install"

script:
  - "npx gulp bundle"
  - "npx gulp test"
  - "PGDIR=`pwd`"
  - "cd tests/behave"
  - "source env/bin/activate"
  - "TARGET=file://$PGDIR DRAFT=6 behave"

# whitelist
branches:
  only:
    - master
