sudo: required

language: node_js

node_js:
  - "v8.12.0"

before_install:
  - "sudo pip install --upgrade pip"
  - "sudo pip install selenium"
  - "sudo pip install behave"

install:
  - "npm install"

script:
  - "gulp bundle"
  - "gulp test"
  - "PGDIR=`pwd`"
  - "cd tests/behave"
  - "TARGET=file://$PGDIR BROWSER=phantomjs behave"

# whitelist
branches:
  only:
    - master
